-- Query 1: Lista de Fornecedores e Volume de Pedidos
SELECT
    cab.CODPARC,
    par.NOMEPARC,
    COUNT(DISTINCT CAB.NUNOTA) AS QTD_PEDIDOS
FROM TGFCAB cab
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
JOIN TGFPAR par ON par.CODPARC = cab.CODPARC
JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
WHERE cab.DTNEG BETWEEN :INI AND :FIN
  AND cab.TIPMOV = 'C'
  AND cab.CODTIPOPER IN (200,227)
  AND NVL(par.FORNECEDOR,'N') = 'S'
  AND CAB.CODEMP IN (:EMPRESA)
  AND (:CODPROD IS NULL OR ITE.CODPROD = :CODPROD)
  AND (:GRUPOPROD IS NULL OR PRO.CODGRUPOPROD = :GRUPOPROD)
  AND (:CODPARC IS NULL OR CAB.CODPARC = :CODPARC)
GROUP BY cab.CODPARC, par.NOMEPARC
ORDER BY par.NOMEPARC
