-- Resumo de Contas a Pagar (Pendentes)
-- Agrupa os compromissos financeiros por período
SELECT 
    CODEMP,
    SUM(VLRDESDOB) AS TOTAL_PENDENTE,
    COUNT(NUFIN) AS QTD_TITULOS,
    CASE 
        WHEN DTVENC < TRUNC(SYSDATE) THEN 'ATRASADO'
        WHEN DTVENC <= TRUNC(SYSDATE) + :DIAS_HORIZONTE THEN 'NO_PRAZO'
        ELSE 'FUTURO'
    END AS STATUS_VENCIMENTO
FROM TGFFIN 
WHERE RECDESP = -1 
  AND DHBAIXA IS NULL
  AND PROVISAO = 'N'
GROUP BY 
    CODEMP,
    CASE 
        WHEN DTVENC < TRUNC(SYSDATE) THEN 'ATRASADO'
        WHEN DTVENC <= TRUNC(SYSDATE) + :DIAS_HORIZONTE THEN 'NO_PRAZO'
        ELSE 'FUTURO'
    END
ORDER BY CODEMP, STATUS_VENCIMENTO
