-- Query 1: Resumo de Popularidade e Perda de Vendas (Demanda Reprimida)
WITH BASE_ORCAMENTO AS (
    SELECT
        I.CODPROD,
        COALESCE(P.DESCRPROD, 'SEM DESCRIÇÃO') AS DESCRPROD,
        COALESCE(I.QTDNEG, 0) AS QTDNEG,
        COALESCE(I.VLRUNIT, 0) AS VLRUNIT,
        C.DTNEG,
        COALESCE((
            SELECT EH.ESTOQUE_NA_DATA
            FROM TBL_ESTOQUE_HISTORICO_PRODUTO EH
            WHERE EH.CODPROD = I.CODPROD
              AND EH.DATA_MOVIMENTACAO <= TRUNC(C.DTNEG)
            ORDER BY EH.DATA_MOVIMENTACAO DESC
            FETCH FIRST 1 ROWS ONLY
        ), 0) AS ESTOQUE_HISTORICO
    FROM TGFITE I
    JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA
    LEFT JOIN TGFPRO P ON P.CODPROD = I.CODPROD
    LEFT JOIN TGFPAR PAR ON PAR.CODPARC = C.CODPARC
    WHERE 
        C.CODTIPOPER IN (900, 1000)
        AND C.VLRNOTA > 0
        AND TRUNC(C.DTNEG) BETWEEN :INI AND :FIN
        AND (:EMPRESA IS NULL OR C.CODEMP = :EMPRESA)
        AND (:CODTIPVENDA IS NULL OR C.CODTIPOPER = :CODTIPVENDA)
        AND (:VENDEDOR IS NULL OR C.CODVEND = :VENDEDOR)
        AND (:CODTIPPARC IS NULL OR PAR.CODTIPPARC = :CODTIPPARC)
        AND (:MOTIVOCANCEL IS NULL OR C.AD_CODMOTIVO = :MOTIVOCANCEL)
        AND (:CODPROD IS NULL OR I.CODPROD = :CODPROD)
        AND (:CODGRUPOPROD IS NULL OR P.CODGRUPOPROD = :CODGRUPOPROD)
),

-- Cálculo da moda da quantidade negociada
MODA_QTD AS (
    SELECT 
        CODPROD, 
        QTDNEG,
        ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY COUNT(*) DESC) AS RN
    FROM BASE_ORCAMENTO
    GROUP BY CODPROD, QTDNEG
)

SELECT
    B.CODPROD,
    MAX(B.DESCRPROD) AS DESCRPROD,
    COUNT(*) AS TOTAL_ORCADO,
    SUM(CASE WHEN B.ESTOQUE_HISTORICO < B.QTDNEG THEN 1 ELSE 0 END) AS QTDE_SEM_ESTOQUE,
    CASE 
        WHEN COUNT(*) > 0 THEN ROUND(SUM(CASE WHEN B.ESTOQUE_HISTORICO < B.QTDNEG THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)
        ELSE 0
    END AS PERC_SEM_ESTOQUE,
    MAX(CASE WHEN M.RN = 1 THEN M.QTDNEG ELSE NULL END) AS MODA_QTDNEG, -- Moda real
    ROUND(AVG(B.QTDNEG), 2) AS MEDIA_QTDNEG, -- Média real
    ROUND(SUM(
        CASE 
            WHEN B.ESTOQUE_HISTORICO < B.QTDNEG 
            THEN (B.QTDNEG * B.VLRUNIT) 
            ELSE 0 
        END
    ), 2) AS VALOR_TOTAL_PERDIDO
FROM BASE_ORCAMENTO B
LEFT JOIN MODA_QTD M ON M.CODPROD = B.CODPROD AND M.RN = 1
GROUP BY B.CODPROD
HAVING SUM(CASE WHEN B.ESTOQUE_HISTORICO < B.QTDNEG THEN 1 ELSE 0 END) > 0
ORDER BY VALOR_TOTAL_PERDIDO DESC, QTDE_SEM_ESTOQUE DESC, TOTAL_ORCADO DESC
FETCH FIRST 100 ROWS ONLY
