-- Query 2: Detalhamento (Drilldown) de orçamentos por produto
WITH BASE_DRILLDOWN AS (
    SELECT
        C.NUNOTA,
        C.DTNEG,
        C.AD_NOMECLIENTE AS CLIENTE,
        I.SEQUENCIA,
        I.CODPROD,
        P.DESCRPROD,
        I.QTDNEG,
        I.VLRUNIT,
        I.VLRTOT,
        NVL((
            SELECT EH.ESTOQUE_NA_DATA
            FROM TBL_ESTOQUE_HISTORICO_PRODUTO EH
            WHERE EH.CODPROD = I.CODPROD
              AND EH.DATA_MOVIMENTACAO <= TRUNC(C.DTNEG)
            ORDER BY EH.DATA_MOVIMENTACAO DESC
            FETCH FIRST 1 ROWS ONLY
        ), 0) AS ESTOQUE_NA_DATA,
        CASE WHEN NVL((
            SELECT EH.ESTOQUE_NA_DATA
            FROM TBL_ESTOQUE_HISTORICO_PRODUTO EH
            WHERE EH.CODPROD = I.CODPROD
              AND EH.DATA_MOVIMENTACAO <= TRUNC(C.DTNEG)
            ORDER BY EH.DATA_MOVIMENTACAO DESC
            FETCH FIRST 1 ROWS ONLY
        ), 0) < I.QTDNEG THEN 'INSUFICIENTE' ELSE 'OK' END AS STATUS_ESTOQUE
    FROM TGFITE I
    JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA
    LEFT JOIN TGFPRO P ON P.CODPROD = I.CODPROD
    LEFT JOIN TGFPAR PAR ON PAR.CODPARC = C.CODPARC
    WHERE 
        C.CODTIPOPER IN (900, 1000)
        AND C.VLRNOTA > 0
        AND TRUNC(C.DTNEG) BETWEEN :INI AND :FIN
        AND (:EMPRESA IS NULL OR C.CODEMP = :EMPRESA)
        AND (:CODTIPVENDA IS NULL OR C.CODTIPOPER = :CODTIPVENDA)
        AND (:VENDEDOR IS NULL OR C.CODVEND = :VENDEDOR)
        AND (:CODTIPPARC IS NULL OR PAR.CODTIPPARC = :CODTIPPARC)
        AND (:MOTIVOCANCEL IS NULL OR C.AD_CODMOTIVO = :MOTIVOCANCEL)
)

SELECT
    B.NUNOTA,
    B.DTNEG,
    B.CLIENTE,
    B.SEQUENCIA,
    B.CODPROD,
    B.DESCRPROD,
    B.QTDNEG,
    B.VLRUNIT,
    B.VLRTOT,
    B.ESTOQUE_NA_DATA,
    B.STATUS_ESTOQUE
FROM BASE_DRILLDOWN B
WHERE B.CODPROD = :CODPROD
ORDER BY B.DTNEG DESC
