-- Resumo de Fluxo de Compromissos (Receber vs Pagar)
-- Compara os compromissos financeiros para detectar desequilíbrio no capital de giro
SELECT 
    CODEMP,
    CASE WHEN RECDESP = 1 THEN 'RECEBER (VENDAS)' ELSE 'PAGAR (COMPRAS)' END AS TIPO,
    SUM(VLRDESDOB) AS TOTAL,
    COUNT(NUFIN) AS QTD_TITULOS,
    CASE 
        WHEN DTVENC < TRUNC(SYSDATE) THEN 'ATRASADO'
        WHEN DTVENC <= TRUNC(SYSDATE) + :DIAS_HORIZONTE THEN 'NO_PRAZO'
        ELSE 'FUTURO'
    END AS STATUS_VENCIMENTO
FROM TGFFIN 
WHERE DHBAIXA IS NULL
  AND PROVISAO = 'N'
  AND RECDESP IN (1, -1)
GROUP BY 
    CODEMP,
    RECDESP,
    CASE 
        WHEN DTVENC < TRUNC(SYSDATE) THEN 'ATRASADO'
        WHEN DTVENC <= TRUNC(SYSDATE) + :DIAS_HORIZONTE THEN 'NO_PRAZO'
        ELSE 'FUTURO'
    END
ORDER BY CODEMP, RECDESP DESC, STATUS_VENCIMENTO
