-- Valorização de Estoque Total
-- Calcula o valor financeiro imobilizado em estoque por empresa
SELECT 
    E.CODEMP,
    EMP.NOMEFANTASIA AS EMPRESA,
    SUM(E.ESTOQUE * C.CUSREP) AS VALOR_TOTAL_ESTOQUE,
    COUNT(DISTINCT E.CODPROD) AS QTD_ITENS_COM_SALDO
FROM TGFEST E
JOIN TGFCUS C ON E.CODPROD = C.CODPROD AND E.CODEMP = C.CODEMP
JOIN TSIEMP EMP ON E.CODEMP = EMP.CODEMP
WHERE C.DHALTER = (
    SELECT MAX(X.DHALTER) 
    FROM TGFCUS X 
    WHERE X.CODPROD = C.CODPROD 
      AND X.CODEMP = C.CODEMP
)
AND E.ESTOQUE > 0
GROUP BY E.CODEMP, EMP.NOMEFANTASIA
ORDER BY E.CODEMP
