-- Query 2: Grupos de Produtos comprados por Fornecedor
SELECT
    gru.CODGRUPOPROD,
    gru.DESCRGRUPOPROD,
    SUM(ite.QTDNEG)   AS QTD,
    SUM(ite.VLRTOT)   AS VLRTOT,
    COUNT(DISTINCT cab.NUNOTA) AS QTD_PEDIDOS
FROM TGFITE ite
JOIN TGFCAB cab  ON cab.NUNOTA = ite.NUNOTA
JOIN TGFPRO pro  ON pro.CODPROD = ite.CODPROD
JOIN TGFGRU gru  ON gru.CODGRUPOPROD = pro.CODGRUPOPROD
WHERE cab.CODPARC = :CODPARC
  AND cab.DTNEG   BETWEEN :INI AND :FIN
  AND cab.TIPMOV  = 'C'
  AND cab.CODTIPOPER IN (200,227)
  AND cab.CODEMP IN (:EMPRESA)
GROUP BY gru.CODGRUPOPROD, gru.DESCRGRUPOPROD
ORDER BY gru.DESCRGRUPOPROD
